spring.application.name=job-email-agent

logging.level.root=INFO

# SQLite DB Configuration
spring.datasource.url=jdbc:sqlite:job-email-agent.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate SQLite Dialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Auto create/update tables
spring.jpa.hibernate.ddl-auto=none

# Show SQL queries in logs
spring.jpa.show-sql=true

# Avoid metadata lookup issues
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false