spring.application.name=job-email-agent

spring.datasource.url=jdbc:sqlite:job-email-agent.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update

logging.level.root=INFO